### ISSUE TITLE
sensornet report compilation error in Arduino1.0.1

### ISSUE THREAD

**Issue by Ardidrones** [maniacbug/RF24#11]
When trying to compile sensor net example from the zip it reports a eeprom_update_block is not declared.

**Comment by probonopd** [comment]
I get the same using Arduino 1.0.2:

nodeconfig.cpp: In function ‘void nodeconfig_listen()’:
nodeconfig.cpp:74: error: ‘eeprom_update_block’ was not declared in this scope
nodeconfig.cpp:83: error: ‘eeprom_update_block’ was not declared in this scope
nodeconfig.cpp:101: error: ‘eeprom_update_block’ was not declared in this scope

**Comment by DevGW** [comment]
Same using Arduino 1.0.3 ...

I noticed on your blog back in Nov. you mentioned needing to fix this ... did that ever get done and just not updated on here or do you know of a workaround?

**Comment by seowcy** [comment]
Same errors encountered here, is there any way to avoid this problem at the very least? :)

**Comment by DevGW** [comment]
@seowcy I have a pull request in that fixes this issue and is working on 1.0.1 and 1.5.2 ... I don't know if this is being maintained any more so are welcome to grab my fork from my repo and see if that makes a difference.  I only updated the code for sensornet for the fix so not sure any of the other examples will work or not ... I believe they all do.

**Comment by seowcy** [comment]
@RWSDev Thanks! I'm now encountering problems with Button and Timer when compiling the code though. Not sure what the problem is. Any idea?
![screenshot1](https://f.cloud.github.com/assets/3659208/180210/2663c470-7c27-11e2-8c96-d14bcb6f00a7.png)

**Comment by DevGW** [comment]
for sensornet to compile, you will need to download all the libraries from maniacbug that are included in the top of the .ino ... 

```
#include <Tictocs.h>
#include <Button.h>
#include <TictocTimer.h>
```

**Comment by seowcy** [comment]
Thanks for the help! It works now! I will contact you if I need more help.

Thanks again!

**Comment by tott** [comment]
@RWSDev: I have the same issue with those missing libraries. Where did you find them?

**Comment by tott** [comment]
Ok, I just found it. For reference:
You need to clone https://github.com/maniacbug/Tictocs.git in your libraries folder and restart the Arduino IDE. Then the examples will compile

**Comment by Jimster1** [comment]
Hi I'm using 1.0.3, and I've downlaod the Tictocs.git but I'm im still getting the errors:
nodeconfig.cpp: In function ‘void nodeconfig_listen()’:
nodeconfig.cpp:74: error: ‘eeprom_update_block’ was not declared in this scope
nodeconfig.cpp:83: error: ‘eeprom_update_block’ was not declared in this scope
nodeconfig.cpp:101: error: ‘eeprom_update_block’ was not declared in this scope

**Comment by tott** [comment]
@Jimster1 I used https://github.com/RWSDev/RF24Network which included a pull request that had some fixes for the compilation issue. Did you use this version as well or patched in the pull request?

**Comment by Jimster1** [comment]
@tott Thats awesome, that now works a treat. sorry forr the slow reply I've been away on holiday.

**Comment by arabeei** [comment]
@tott that was very help full.. thanks man.
